version: '3.7'

services:
  app:
    container_name: customer-app
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run start:dev
    ports:
      - 3333:3000
    volumes:
      - .:/usr/src/app
    depends_on:
      - redis
    networks:
      - customer-network

  redis:
    image: redis:6.2-alpine
    container_name: customer-redis
    command: redis-server --requirepass cu5t0m3rr3d1s
    ports:
      - 6680:6379
    volumes:
      - customer-redis-data:/data
    networks:
      - customer-network

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: customer-redis-commander
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=cu5t0m3rr3d1s
    ports:
      - 8091:8081
    networks:
      - customer-network

networks:
  customer-network:
    name: customer-network
    driver: bridge

volumes:
  customer-redis-data:
    name: customer-redis-data